# Generated by Django 3.2.6 on 2021-08-22 14:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0003_alter_taskmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
