# Generated by Django 3.2.12 on 2022-03-26 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0008_rename_user_id_user_address_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_details',
            name='payment_id',
        ),
        migrations.RemoveField(
            model_name='order_details',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='order_items',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='order_items',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='inventory_id',
        ),
        migrations.RemoveField(
            model_name='shopping_session',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='user_address',
            name='userid',
        ),
        migrations.RemoveField(
            model_name='user_payment',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='cart_item',
        ),
        migrations.DeleteModel(
            name='discount',
        ),
        migrations.DeleteModel(
            name='order_details',
        ),
        migrations.DeleteModel(
            name='order_items',
        ),
        migrations.DeleteModel(
            name='payment_details',
        ),
        migrations.DeleteModel(
            name='product',
        ),
        migrations.DeleteModel(
            name='product_category',
        ),
        migrations.DeleteModel(
            name='product_inventory',
        ),
        migrations.DeleteModel(
            name='shopping_session',
        ),
        migrations.DeleteModel(
            name='user_address',
        ),
        migrations.DeleteModel(
            name='user_new',
        ),
        migrations.DeleteModel(
            name='user_payment',
        ),
    ]
